version: '2'

services:

### Applications Code Container #############################

    applications:
      image: tianon/true
      volumes:
        - ./:/downloader
#        - /home/ximlor/storage/:/storage

### Py Container #########################################

    py:
      build: ./docker/py
      volumes_from:
        - applications
      tty: false
